Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [3]:
for i in list_:
    print(type(i))


for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [4]:
array_list = np.array(object = list_, dtype = int)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [5]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [8]:
print(num_array.shape)
num_array.size

(2, 3)


6

In [10]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
mat = np.zeros((3,3))
print(mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])