In [1]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np
arr = np.arange(0,6)
print(arr)
arr.dtype

[0 1 2 3 4 5]


dtype('int64')

In [2]:
#2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
arr.dtype

dtype('float64')

In [3]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([(5+10j),(12+20j),(50+10000j)])
arr.dtype

dtype('complex128')

In [4]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.arange(0,6)
print(arr.dtype)
arr = arr.astype('float32')
arr.dtype

int64


dtype('float32')

In [5]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)
arr = arr.astype('float32')
arr.dtype

float64


dtype('float32')

In [6]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr) :
    return arr.shape, arr.size, arr.dtype

array_attributes(arr)

((3,), 3, dtype('float32'))

In [7]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_attributes(arr) :
    return arr.ndim

array_attributes(arr)

1

In [8]:
 #8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.size * item_size
    return item_size, total_size
arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size_info(arr)

(8, 48)

In [9]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides

print(arr)
array_strides(arr)

[[1 2 3]
 [4 5 6]]


(24, 8)

In [10]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

print(arr)
shape_stride_relationship(arr)

[[1 2 3]
 [4 5 6]]


((2, 3), (24, 8))

In [11]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
    arr1 = np.zeros(n)
    return arr1

create_zeros_array(5)

array([0., 0., 0., 0., 0.])

In [12]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs
#and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(m,n):
    mat = np.ones((m,n))
    return mat

create_ones_matrix(3,4)


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
def generate_range_array(a,b,c):
    arr = np.arange(a,b,c)
    return arr

generate_range_array(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [14]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start, stop,num):
    arr = np.linspace(start, stop,num)
    return arr
generate_linear_space(2.1,5.2,10)

array([2.1       , 2.44444444, 2.78888889, 3.13333333, 3.47777778,
       3.82222222, 4.16666667, 4.51111111, 4.85555556, 5.2       ])

In [15]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
#identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    arr = np.eye(n)
    return arr
create_identity_matrix(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
#16. Write a function that takes a Python list and converts it into a NumPy array
def list_to_array(l):
    arr = np.array(l)
    return arr
l = [1, 2, 3, 4, 5]
list_to_array(l)

array([1, 2, 3, 4, 5])

In [17]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
print(arr)
arr2 = arr.view
print(arr2)

[[1 2 3]
 [4 5 6]]
<built-in method view of numpy.ndarray object at 0x7a77528926d0>


In [18]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
concatenate_arrays(arr1, arr2, axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9,10], [10, 11, 12,14]])
concat=np.concatenate((arr1, arr2), axis=1)
concat

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 10, 11, 12, 14]])

In [20]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.
def vstack_arrays(arrays):
   return np.vstack(arrays)

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr3 = np.array([[13, 14, 15], [16, 17, 18]])

vstack_arrays([arr1, arr2, arr3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [21]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def generate_range_array(a,b,c):
    arr = np.arange(a,b+1,c)
    return arr

generate_range_array(2,20,3)

array([ 2,  5,  8, 11, 14, 17, 20])

In [22]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1(inclusive).
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
arr_log =np.logspace(start=0, stop=3, num=5)
arr_log

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [24]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data)
df

0   1   2
0  29  79  52
1  58  11  27
2  42  20  15
3  33  28  85
4   5  24  33

In [25]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
import pandas as pd

def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {'A': [1, -2, 3, -4, 5], 'B': [5, -6, 7, -8, 9]}
df = pd.DataFrame(data)
print(df)
df = replace_negatives_with_zeros(df, 'A')
print(df)


   A  B
0  1  5
1 -2 -6
2  3  7
3 -4 -8
4  5  9
   A  B
0  1  5
1  0 -6
2  3  7
3  0 -8
4  5  9


In [26]:
#26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [27]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[(1,2)]

6

In [28]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr>5]

array([ 8, 10,  7])

In [29]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [30]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [31]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements(arr_2d, indices):
    return arr_2d[indices[:, 0], indices[:, 1]]
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices = np.array([[0, 1],
                    [1, 2],
                    [2, 0]])
extracted_elements = extract_elements(arr_2d, indices)

print(extracted_elements)


[2 6 7]


In [32]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def filter_greater_than_threshold(arr_1d, threshold):
    return arr_1d[arr_1d > threshold]
arr_1d = np.array([1, 5, 8, 3, 7, 2, 6, 9, 4])
threshold = 5
filtered_elements = filter_greater_than_threshold(arr_1d, threshold)
print(filtered_elements)


[8 7 6 9]


In [33]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
import numpy as np

def extract_elements_3d(arr_3d, indices_x, indices_y, indices_z):
    return arr_3d[indices_x, indices_y, indices_z]
arr_3d = np.array([[[ 1,  2,  3],
                    [ 4,  5,  6],
                    [ 7,  8,  9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])
indices_x = np.array([0, 1, 2])
indices_y = np.array([1, 0, 2])
indices_z = np.array([2, 1, 0])
extracted_elements = extract_elements_3d(arr_3d, indices_x, indices_y, indices_z)

print(extracted_elements)


[ 6 11 25]


In [34]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np

def filter_elements_with_two_conditions(arr, condition1, condition2):
    boolean_mask = condition1(arr) & condition2(arr)
    return arr[boolean_mask]
arr = np.array([1, 5, 8, 3, 7, 2, 6, 9, 4])

condition1 = lambda x: x > 3
condition2 = lambda x: x < 8

filtered_elements = filter_elements_with_two_conditions(arr, condition1, condition2)

print(filtered_elements)


[5 7 6 4]


In [35]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_elements_2d(arr_2d, row_indices, col_indices):

    return arr_2d[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

extracted_elements = extract_elements_2d(arr_2d, row_indices, col_indices)

print(extracted_elements)


[2 6 7]


In [36]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr_plus_5 = arr + 5

print(arr_plus_5)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr1 = np.array([[2],
                  [3],
                  [4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

result = arr2 * arr1

print(result)


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [38]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

arr1_reshaped = arr1[:, :arr2.shape[1]]
result = arr2 + arr1_reshaped

print(result)



[[ 6  8 10]
 [ 9 11 13]
 [12 14 16]
 [15 17 19]]


In [39]:
#39 Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.array([[1],
                 [2],
                 [3]])

arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2

print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [40]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.


In [41]:
#41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)


[2.5 3.5 4.5]


In [42]:
#42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
max = np.max(arr, axis=1)
print(max)

[3 6]


In [43]:
#43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
indices_max = np.argmax(arr, axis=0)
print(indices_max)

[1 1 1]


In [44]:
#44. For the given array, apply custom function to calculate moving sum along rows.

In [45]:
#45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
arr%2==0

array([[ True,  True,  True],
       [False, False, False]])

In [46]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
arr = np.array([2, 4, 6,3, 5, 7])

matrixx = np.asmatrix(arr.reshape(2,3))
matrixx

matrix([[2, 4, 6],
        [3, 5, 7]])

In [47]:
#47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def flatten(mat):
  matt = mat.flatten()
  return matt

flatten(input_matrix)

array([1, 2, 3, 4, 5, 6])

In [48]:
#48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print(concatenate_arrays(array1,array2, axis=0))
concatenate_arrays(array1,array2, axis=1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [49]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.split(original_array,3, axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [50]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
def insert_and_delete(arr, insert_indices, insert_values, delete_indices):
    arr = np.insert(arr, insert_indices, insert_values)
    arr = np.delete(arr, delete_indices)

    return arr
original_array = np.array([1, 2, 3, 4, 5])
insert_indices = [1, 3]
insert_values = [9, 8]
delete_indices = [2, 4]

result = insert_and_delete(original_array, insert_indices, insert_values, delete_indices)

print(result)


[1 9 3 4 5]


In [51]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
arr1 = np.random.randint(0, 10, size=10)
arr2 = np.arange(1, 11)
print(arr1)
print(arr2)
result = arr1 + arr2
result

[5 9 6 7 0 3 5 7 0 2]
[ 1  2  3  4  5  6  7  8  9 10]


array([ 6, 11,  9, 11,  5,  9, 12, 15,  9, 12])

In [52]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
print(arr1)
print(arr2)
result = arr1 - arr2
result

[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]


array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [53]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
arr1 = np.random.randint(0,1000,size=5)
print(arr1)
arr2 = np.arange(1,6)
print(arr2)
result = arr1*arr2
result

[990 865 361 563 420]
[1 2 3 4 5]


array([ 990, 1730, 1083, 2252, 2100])

In [54]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)
result = arr1/arr2
result

array([2., 2., 2., 2., 2.])

In [55]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed.
#Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1 = np.arange(1,6)
arr2 = np.arange(5,0,-1)
result = arr1**arr2
result

array([ 1, 16, 27, 16,  5])

In [56]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_substring_occurrences(arr, substring):
    count_per_element = np.char.count(arr, substring)
    total_count = np.sum(count_per_element)

    return total_count
substring = 'hello'

result = count_substring_occurrences(arr, substring)

print(result)


3


In [57]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [58]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def replace_substring(arr, old_substring, new_substring):
  new_arr = np.char.replace(arr, old_substring, new_substring)

  return new_arr

print(replace_substring(arr,'banana', 'mango'))

['apple' 'mango' 'grape' 'pineapple']


In [59]:
#59. Write a function that concatenates strings in a NumPy array element-wise

def concatenate_strings(arr1, arr2):
    concatenated = np.char.add(arr1,' ')
    concatenated_array = np.char.add(concatenated,arr2)
    return concatenated_array

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)

print(result)


['Hello Open' 'World AI']


In [60]:
#60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def longest_string_length(arr):
  lengths = np.vectorize(len)(arr)
  lengths_max = np.max(lengths)
  return lengths_max

print(longest_string_length(arr))

9


In [61]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
arr = np.random.randint(1,1000, size=100)
mean_value = np.mean(arr)
median_value = np.median(arr)
variance_value = np.var(arr)
std_deviation_value = np.std(arr)
print("Dataset:", arr)
print("Mean:", mean_value)
print("Median:", median_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation_value)


Dataset: [968 199 878 204 550   4 214 724 241 913 238 160 672 822 894 813 716 193
  10 959 326 802 624 771 466 730 857 774 921 275 422 708 601 431 447 791
 916 285 957 326 341 694 889 801 981   3 430 500 721   5 768 893 133 353
 416 246 956 545 799 692 857 827 502 183 775 761 909 988 897 432 600  17
 105 931 248 132 226 402 805  71 433 672 945 119 680 520 990 178 415 396
  31 760 148 253 612 896 305 338 779 792]
Mean: 548.98
Median: 600.5
Variance: 90911.71960000001
Standard Deviation: 301.51570373696956


In [62]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
dataset = np.random.randint(1,100, size=50)
percentile_25 = np.percentile(dataset, 25)

# Find the 75th percentile
percentile_75 = np.percentile(dataset, 75)
print("Random Numbers:", dataset)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Random Numbers: [73  6 58 39  3 59 42 17 35 67 25  1 23 96 39  1 23 95 72  3 91 48 47 44
 99 88  3 49 61 79 95 65  3 19 36 40 86 39 54 43 18 98 57 79 19 38 91 95
 69 69]
25th Percentile: 23.5
75th Percentile: 72.75


In [63]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
array1 = np.random.rand(100)
array2 = np.random.rand(100)

correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

print("Correlation Coefficient:", correlation_coefficient)


Correlation Coefficient: 0.07408478308418186


In [64]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix2)
print("\nMatrix 2:")
print(matrix2)
print('\nresult')
print(result)


Matrix 1:
[[ 7  8]
 [ 9 10]
 [11 12]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

result
[[ 58  64]
 [139 154]]


In [65]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

array = np.random.randint(10, 1001, size=50)

percentile_10th = np.percentile(array, 10)
percentile_50th = np.percentile(array, 50)
percentile_90th = np.percentile(array, 90)
quartile_1st = np.percentile(array, 25)
quartile_3rd = np.percentile(array, 75)

print("Array:", array)
print("10th Percentile:", percentile_10th)
print("50th Percentile (Median):", percentile_50th)
print("90th Percentile:", percentile_90th)
print("1st Quartile:", quartile_1st)
print("3rd Quartile:", quartile_3rd)


Array: [942 564 345 524 329 652 181 819 942 999 163 171 598 684 785 457 351 684
  99 502 509 231 338 881 977  89 226 367 248  20 832 944 393 772 848 498
 283 409 693 853 107 212 622 267 932 641 208 119 220 931]
10th Percentile: 158.60000000000002
50th Percentile (Median): 500.0
90th Percentile: 933.0
1st Quartile: 235.25
3rd Quartile: 781.75


In [66]:
#66. Create a NumPy array of integers and find the index of a specific element.
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Find the index of a specific element (e.g., 40)
element_to_find = 40
index = np.where(array == element_to_find)[0]
print(index)

[3]


In [67]:
#67. Generate a random NumPy array and sort it in ascending order
random_array = np.random.randint(1, 100, size=10)
sorted_array = np.sort(random_array)

print(random_array)
print("Sorted Array ", sorted_array)


[17 11 35 79 77 79 79 11 34 39]
Sorted Array  [11 11 17 34 35 39 77 79 79 79]


In [68]:
#68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr>20]

array([25, 42, 30])

In [69]:
#69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3==0]

array([12, 15])

In [70]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr[(arr>=20) & (arr<=40)]

array([20, 30, 40])

In [71]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(byte_order)

=


In [72]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3])
arr.byteswap(True)

print("Byte Swapped Array:", arr)

Byte Swapped Array: [ 72057594037927936 144115188075855872 216172782113783808]


In [73]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

print("Original Array:", arr)
print("Swapped Byte Order Array:", swapped_arr)


Original Array: [1 2 3]
Swapped Byte Order Array: [16777216 33554432 50331648]


In [74]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

system_endianness = np.dtype(np.int32).byteorder
if system_endianness == '=':
    swapped_arr = arr.copy()
else:
    swapped_arr = arr.newbyteorder()

print("Original Array:", arr)
print("System Endianness:", system_endianness)
print("Swapped Byte Order Array:", swapped_arr)


Original Array: [1 2 3]
System Endianness: =
Swapped Byte Order Array: [1 2 3]


In [75]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`
arr = np.array([1, 2, 3], dtype=np.int32)


In [79]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr1 = np.arange(1, 11)

copy_arr = np.copy(arr1)

copy_arr[0] = 99

print(arr1)
print(copy_arr)


[ 1  2  3  4  5  6  7  8  9 10]
[99  2  3  4  5  6  7  8  9 10]


In [82]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
matrix = np.random.randint(0, 10, size=(3, 3))

view_slice = matrix[1:, 1:]

view_slice[0, 0] = 99

print('Original\n',matrix)
print('\nView Slice\n',view_slice)


Original
 [[ 4  8  7]
 [ 8 99  2]
 [ 1  2  5]]

View Slice
 [[99  2]
 [ 2  5]]


In [83]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:3, 1:3]

view_b += 5

array_a, view_b


(array([[ 1,  2,  3],
        [ 4, 10, 11],
        [ 7, 13, 14],
        [10, 11, 12]]),
 array([[10, 11],
        [13, 14]]))

In [84]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 99
orig_array, reshaped_view


(array([[99,  2,  3,  4],
        [ 5,  6,  7,  8]]),
 array([[99,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]]))

In [85]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

data = np.random.randint(0, 10, size=(3, 4))
data_copy = np.copy(data[data > 5])
if data_copy.size > 0:
    data_copy[0] = 99

data, data_copy


(array([[5, 1, 3, 6],
        [1, 1, 7, 5],
        [4, 6, 6, 5]]),
 array([99,  7,  6,  6]))

In [86]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
addition_result = A + B
subtraction_result = A - B

# Print the results
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition of A and B:")
print(addition_result)
print("\nSubtraction of A and B:")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition of A and B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction of A and B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [87]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
C = np.random.randint(0, 10, size=(3, 2))
D = np.random.randint(0, 10, size=(2, 4))

result = C @ D

print("Matrix C (3x2):")
print(C)
print("\nMatrix D (2x4):")
print(D)
print("\nResult of matrix multiplication (C @ D):")
print(result)


Matrix C (3x2):
[[2 2]
 [7 1]
 [6 0]]

Matrix D (2x4):
[[6 0 3 6]
 [6 9 5 7]]

Result of matrix multiplication (C @ D):
[[24 18 16 26]
 [48  9 26 49]
 [36  0 18 36]]


In [90]:
#83. Create a matrix `E` and find its transpose.
E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

transpose_E = E.T
print("Matrix E:")
print(E)
print("\nTranspose of matrix E:")
print(transpose_E)


Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of matrix E:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [89]:
#84. Generate a square matrix `F` and compute its determinant.
F = np.array([[3, 1, 4],
              [1, 5, 9],
              [2, 6, 5]])

det_F = np.linalg.det(F)

print("Matrix F:\n", F)
print("\nDeterminant of Matrix F:", det_F)


Matrix F:
 [[3 1 4]
 [1 5 9]
 [2 6 5]]

Determinant of Matrix F: -90.0


In [88]:
#85. Create a square matrix `G` and find its inverse
G = np.array([[4, 7, 2],
              [1, 5, 3],
              [8, 6, 9]])
G_inv = np.linalg.inv(G)

print("Matrix G:\n", G)
print("\nInverse of Matrix G:\n", G_inv)


Matrix G:
 [[4 7 2]
 [1 5 3]
 [8 6 9]]

Inverse of Matrix G:
 [[ 0.1862069  -0.35172414  0.07586207]
 [ 0.10344828  0.13793103 -0.06896552]
 [-0.23448276  0.22068966  0.08965517]]
